server:
  servlet:
    encoding:
      force-response: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost/db_example

    username: springuser
    password: 1234
jwt:
  secret: hello.world.ee.ff
  expiredMs: 60000
